//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointments
    {
        public int Id { get; set; }
        public int tm_id { get; set; }
        public System.DateTime appDate { get; set; }
        public Nullable<System.DateTime> realDate { get; set; }
    
        public virtual treatment_plan treatment_plan { get; set; }
    }
}
