//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generalDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cdentalEntities : DbContext
    {
        public cdentalEntities()
            : base("name=cdentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<clinical_history> clinical_history { get; set; }
        public virtual DbSet<ensurance> ensurance { get; set; }
        public virtual DbSet<images> images { get; set; }
        public virtual DbSet<institutions> institutions { get; set; }
        public virtual DbSet<medicines> medicines { get; set; }
        public virtual DbSet<operators> operators { get; set; }
        public virtual DbSet<operators_stats> operators_stats { get; set; }
        public virtual DbSet<pathologies> pathologies { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<patient_record> patient_record { get; set; }
        public virtual DbSet<payment_history> payment_history { get; set; }
        public virtual DbSet<procedures> procedures { get; set; }
        public virtual DbSet<receivables> receivables { get; set; }
        public virtual DbSet<specialities> specialities { get; set; }
        public virtual DbSet<treatment_plan> treatment_plan { get; set; }
        public virtual DbSet<treatments> treatments { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
