//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class divisions
    {
        public divisions()
        {
            this.patient = new HashSet<patient>();
        }
    
        public int div_id { get; set; }
        public int div_instId { get; set; }
        public string div_name { get; set; }
        public Nullable<int> idInstitution { get; set; }
    
        public virtual institutions institutions { get; set; }
        public virtual ICollection<patient> patient { get; set; }
    }
}
