//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class institutions
    {
        public institutions()
        {
            this.divisions = new HashSet<divisions>();
        }
    
        public int ins_id { get; set; }
        public string ins_name { get; set; }
        public string ins_type { get; set; }
    
        public virtual ICollection<divisions> divisions { get; set; }
    }
}
