//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicines
    {
        public int med_id { get; set; }
        public string med_composition { get; set; }
        public string med_commercial { get; set; }
        public Nullable<float> med_dose { get; set; }
        public Nullable<float> med_weightdoserelation { get; set; }
        public string med_presentation { get; set; }
        public Nullable<float> med_age { get; set; }
        public string med_type { get; set; }
    }
}
