//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class operators_stats
    {
        public int os_id { get; set; }
        public int os_opid { get; set; }
        public int os_spid { get; set; }
        public int os_speed { get; set; }
        public int os_presition { get; set; }
    
        public virtual operators operators { get; set; }
        public virtual specialities specialities { get; set; }
    }
}
