//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class operators
    {
        public int op_id { get; set; }
        public string op_names { get; set; }
        public string op_lastn { get; set; }
        public string op_phone1 { get; set; }
        public string op_phone2 { get; set; }
        public string op_email { get; set; }
        public string op_address { get; set; }
        public Nullable<System.DateTime> op_graddate { get; set; }
        public string op_stdlvl { get; set; }
        public Nullable<System.DateTime> op_ingdate { get; set; }
    }
}
