//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public int pac_id { get; set; }
        public string pac_ced { get; set; }
        public string pac_name { get; set; }
        public string pac_lastn { get; set; }
        public Nullable<System.DateTime> pac_born { get; set; }
        public string pac_race { get; set; }
        public string pac_phone1 { get; set; }
        public string pac_phone2 { get; set; }
        public string pac_address { get; set; }
        public string pac_job { get; set; }
        public string pac_school { get; set; }
        public string pac_ensur { get; set; }
    }
}
