//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialities
    {
        public specialities()
        {
            this.operators_stats = new HashSet<operators_stats>();
            this.treatments = new HashSet<treatments>();
        }
    
        public int sp_id { get; set; }
        public string sp_name { get; set; }
        public string sp_type { get; set; }
    
        public virtual ICollection<operators_stats> operators_stats { get; set; }
        public virtual ICollection<treatments> treatments { get; set; }
    }
}
