//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatments
    {
        public int tr_id { get; set; }
        public string tr_name { get; set; }
        public int tr_espid { get; set; }
        public Nullable<int> tr_patid { get; set; }
        public Nullable<float> tr_baseprice { get; set; }
    }
}
