//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int usr_id { get; set; }
        public string username { get; set; }
        public string passwd_md5 { get; set; }
        public string role { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public string institution { get; set; }
    }
}
