//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core_service.mainDB_ref {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mainDB_ref.ImainDB_service")]
    public interface ImainDB_service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImainDB_service/DoWork", ReplyAction="http://tempuri.org/ImainDB_service/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImainDB_service/DoWork", ReplyAction="http://tempuri.org/ImainDB_service/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImainDB_service/getUsername", ReplyAction="http://tempuri.org/ImainDB_service/getUsernameResponse")]
        string getUsername(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImainDB_service/getUsername", ReplyAction="http://tempuri.org/ImainDB_service/getUsernameResponse")]
        System.Threading.Tasks.Task<string> getUsernameAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImainDB_serviceChannel : core_service.mainDB_ref.ImainDB_service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImainDB_serviceClient : System.ServiceModel.ClientBase<core_service.mainDB_ref.ImainDB_service>, core_service.mainDB_ref.ImainDB_service {
        
        public ImainDB_serviceClient() {
        }
        
        public ImainDB_serviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImainDB_serviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImainDB_serviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImainDB_serviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string getUsername(int ID) {
            return base.Channel.getUsername(ID);
        }
        
        public System.Threading.Tasks.Task<string> getUsernameAsync(int ID) {
            return base.Channel.getUsernameAsync(ID);
        }
    }
}
