//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mainDB_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinical_history
    {
        public int ch_code { get; set; }
        public int ch_pacid { get; set; }
        public string ch_operator { get; set; }
        public string ch_interrog { get; set; }
        public Nullable<System.DateTime> ch_regdate { get; set; }
    }
}
