//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mainDB_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class procedures
    {
        public int pr_id { get; set; }
        public int pr_pacid { get; set; }
        public int pr_opid { get; set; }
        public Nullable<int> pr_tmid { get; set; }
        public int pr_trid { get; set; }
        public string pr_observations { get; set; }
        public Nullable<System.DateTime> pr_plandate { get; set; }
        public Nullable<System.DateTime> pr_procdate { get; set; }
        public string pr_status { get; set; }
        public Nullable<float> pr_genprice { get; set; }
        public Nullable<float> pr_discount { get; set; }
        public string pr_evaluation { get; set; }
    }
}
