//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mainDB_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatment_plan
    {
        public int tm_id { get; set; }
        public int tm_pacid { get; set; }
        public int tm_trid { get; set; }
        public System.DateTime tm_regdate { get; set; }
        public System.DateTime tm_startdate { get; set; }
        public System.DateTime tm_enddate { get; set; }
        public Nullable<float> tm_price { get; set; }
        public string tm_status { get; set; }
    }
}
