//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_dent.core_serviceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="core_serviceRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerNombre", ReplyAction="http://tempuri.org/IService1/obtenerNombreResponse")]
        string obtenerNombre(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerNombre", ReplyAction="http://tempuri.org/IService1/obtenerNombreResponse")]
        System.Threading.Tasks.Task<string> obtenerNombreAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizarNombre", ReplyAction="http://tempuri.org/IService1/actualizarNombreResponse")]
        bool actualizarNombre(int eID, string nuevonombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizarNombre", ReplyAction="http://tempuri.org/IService1/actualizarNombreResponse")]
        System.Threading.Tasks.Task<bool> actualizarNombreAsync(int eID, string nuevonombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : e_dent.core_serviceRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<e_dent.core_serviceRef.IService1>, e_dent.core_serviceRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string obtenerNombre(int ID) {
            return base.Channel.obtenerNombre(ID);
        }
        
        public System.Threading.Tasks.Task<string> obtenerNombreAsync(int ID) {
            return base.Channel.obtenerNombreAsync(ID);
        }
        
        public bool actualizarNombre(int eID, string nuevonombre) {
            return base.Channel.actualizarNombre(eID, nuevonombre);
        }
        
        public System.Threading.Tasks.Task<bool> actualizarNombreAsync(int eID, string nuevonombre) {
            return base.Channel.actualizarNombreAsync(eID, nuevonombre);
        }
    }
}
